---
title: "Rapport final - Projet Bradley Terry"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

```


```{r cars}
install.packages('BradleyTerry2')
install.packages("stringr", dependencies=TRUE)
library(BradleyTerry2)
library(stringr)
library(data.table)

#lecture des données
d2009=read.csv("2009.csv")
d2010=read.csv("2010.csv")
d2011=read.csv("2011.csv")
d2012=read.csv("2012.csv")
d2013=read.csv("2013.csv")
dall<-list(d2009, d2010, d2011, d2012, d2013)
donnees<-rbindlist(dall, fill=TRUE)
donnees<-as.data.frame(donnees)

#On uniformise les noms
donnees$Winner=gsub(". ",x=donnees$Winner,".", fixed=TRUE)
donnees$Loser=gsub(". ",x=donnees$Loser,".", fixed=TRUE)
```


```{r}
#on récupère le nom de tous les joueurs ayant participé à au moins 1 match et leur nombre
joueurs=union(levels(factor(donnees$Winner)), levels(factor(donnees$Loser)))
n<- length(joueurs)

#On remplace la date par le nombre d'année la séparant de 2013
level_date<-function(df){
  df$Date<-2013-year(as.Date(df$Date, format = "%d/%m/%Y"))
  return (df)
}

#On calcule le nombre de jeux gagnés par chacun des joueurs
aggregate_games<-function(df){
  df<-replace(df, is.na(df), 0)
  df$W<-df$W1+df$W2+df$W3+df$W4+df$W5
  df$L<-df$L1+df$L2+df$L3+df$L4+df$L5
  return (df)
}

prepare_df<-function(df){
  df<-level_date((df))
  df<-aggregate_games(df)
  return(df)
}

#on récupère le nombre de jeu gagnés par chaque joueur de la ligne et on les rajoute à la matrice des résultats, coefficienté par la décroissance exponentielle
#si extension=0, on enleve la décroissance exponentielle et on compte par match (et non plus par jeu)
fill_results<- function(line,results, alpha,extension=1){
  w<-(as.numeric(line['W']) * exp(-(alpha*as.numeric(line['Date']))))
  l<-(as.numeric(line['L']) * exp(-(alpha*as.numeric(line['Date']))))
  
  if(extension==0){
    w<-1
    l<-0
  }
  
  results[as.character(line['Winner']),as.character(line['Loser'])] <<- as.numeric(results[as.character(line['Winner']),as.character(line['Loser'])]) + w
  
  results[as.character(line['Loser']),as.character(line['Winner'])] <<- as.numeric(results[as.character(line['Loser']),as.character(line['Winner'])]) + l
}


#on prepre le dataframe puis on crée la matrice des résultats que l'on remplie grace au apply
process_surface<-function(df,alpha,extension=1){
  a<-df
  a<-level_date((a))
  a<-aggregate_games(a)
  
  results <<- data.frame(matrix(ncol = n, nrow = n))
  colnames(results)<<-joueurs
  rownames(results)<<-joueurs
  results<<-replace(results, is.na(results), 0)
  
  apply(a,1,function(x) fill_results(x,results,alpha,extension))
  return(results)
}

#on sépare les matchs selon la surface de jeu et on calcule la matrice des résultats pour chacune des surfaces
process_data<-function(df, alpha, extension=1){
  X <- split(df,df$Surface)
  Y<-lapply(X,function(x) process_surface(x,alpha,extension))
  return(Y)
}

#simple somme des résultats de chaque surface
simple_merge<-function(df){
  y<-Reduce(`+`,df)
  return (y)
}

#on ajoute aux scores d'une surface les scores des autres, surfaces pondérés par beta
composed_merge<-function(df,beta){
  y<-simple_merge(df)
  v<-lapply(df,function(x) beta*y+(1-beta)*x)
  return (v)
}

#nous avons recodé à la main le calcul des scores par la maximisation de la vraissamblance
bradleyt = function(M){
  assertthat::are_equal(dim(M)[1],dim(M)[2])
  d=dim(M)[1]
  #we set the first score as 1
  scores= c(1,rep(1,d-1))
  old_scores=scores
  for(p in 1:100){
    print(p)
    print(sum(abs(old_scores-scores)))
    print(sum(scores))
    old_scores=scores
    for(i in 2:d){
      yi=sum(M[i,])-M[i,i]
      fact=0
      for (j in 1:d){
        if(j!=i){
          fact=fact+((M[i,j]+M[j,i])/(old_scores[i]+old_scores[j]))
        }
      }
      fact=1/fact
      if(yi==0){scores[i]=0.01}
      else{scores[i]=yi*fact}
    }
     
  }
  return(log(scores))
}
```


```{r}
#process the matrix for each surface, with everygame pondered with exp(-alpha*t) (t=nombre d'ann?es s?parant de l'ann?e actuelle)
alpha<-0.01
z<-process_data(donnees,alpha,extension=1)

#simple sum of the results for every surface
y<-simple_merge(z)
ym=as.matrix(y)
dim(ym)

#matrixes for every surface with the score being 1*main surface score + Beta * (sum of other surfaces score). For example see w$Clay, w$Grass, w$Hard or w$Carpet
beta<-0.1
w<-composed_merge(z,beta)

scores=bradleyt(ym)

#on  obtient le classement croissant des jouers par:
colnames(ym)[order(scores)]

# attribution of a score to each player
dim(ym)
colnames(ym)[591]
ym[591,]
ym[592,]
sum(ym[,591])
for (i in 590:592){
  print(sum(ym[i,]))
}
ym[,591]
bradleyt(ym)

# fonctions indicatrices
ind<-function(x) {
  if (x==0) {
    return(1)
  }
  return(0)
}

ind_2<-function(x) {
  if (x>0) {
    return(1)
  }
  return(0)
}

# comparaison entre les pr?visions et les r?sultats (somme des carr?s)
prediction_quality_carres<-function(scores, results) {
  d1=sapply(1:length(scores),function(i) sapply(1:length(scores),function(j) (scores[i]/(scores[i]+ scores[j]))*(1-ind(results[i,j]+ results[j,i]))))
  d2=sapply(1:length(scores),function(i) sapply(1:length(scores),function(j) results[i,j]/(results[i,j]+ results[j,i]+ind(results[i,j]+ results[j,i]))))
  d3=d1-d2
  d4=sapply(d3, function(x) x^2)
  S=(sum(d4)-(1/4)*length(scores))/2 
  return(S)
}

# comparaison entre les pr?visions et les r?sultats (somme des valeurs absolues)
prediction_quality_valabs<-function(scores, results) {
  d1=sapply(1:length(scores),function(i) sapply(1:length(scores),function(j) (scores[i]/(scores[i]+ scores[j]))*(1-ind(results[i,j]+ results[j,i]))))
  d2=sapply(1:length(scores),function(i) sapply(1:length(scores),function(j) results[i,j]/(results[i,j]+ results[j,i]+ind(results[i,j]+ results[j,i]))))
  d3=d1-d2
  d4=sapply(d3, function(x) abs(x))
  S=(sum(d4)-(1/2)*length(scores))/2
  return(S)
}

# ?cart moyen entre pr?vision et r?sultat
ecart_moyen<- function(scores, results) {
  return(prediction_quality_valabs(scores, results)/sum(results))
}

# proportions de r?sultats conformes au classement
proportion_matchs_bien_predits<-function(scores,results) {
  den=sum(results)
  pred=sapply(1:length(scores),function(i) sapply(1:length(scores),function(j) results[i,j]*ind_2(scores[i]-scores[j])))
  num=sum(pred)
  return (num/den)
}

# trac? en fonction de alpha
fx<-prediction_quality_carres(bradleyt(simple_merge(process_data(donnees,x))),results)
plot(x=seq(0,1,length=50), y=fx)

```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.

