---
title: "Main"
output: pdf_document
---
```{r setup, include=FALSE}
install.packages('BradleyTerry2')
```

```{r}
library(BradleyTerry2)
library(data.table)
d2009=read.csv("2009.csv")
d2010=read.csv("2010.csv")
d2011=read.csv("2011.csv")
d2012=read.csv("2012.csv")
d2013=read.csv("2013.csv")
d2014=read.csv("2014.csv")
dall<-list(d2009, d2010, d2011, d2012, d2013, d2014)
donnees<-rbindlist(dall, fill=TRUE)
donnees<-as.data.frame(donnees)
```

```{r}
#Preprocessing of data
#All players
donnees$Winner=gsub(". ",x=donnees$Winner,".", fixed=TRUE)
gagnants=levels(factor(donnees$Winner))
donnees$Loser=gsub(". ",x=donnees$Loser,".", fixed=TRUE)
joueurs=union(levels(factor(donnees$Winner)), levels(factor(donnees$Loser)))
n<- length(joueurs)
results <- data.frame(matrix(ncol = n, nrow = n))
colnames(results)<-joueurs
rownames(results)<-joueurs

#Victories of gagnants against their opponents
victories<-by(donnees, donnees$Winner, function(x) table(x$Loser))

fill_victories<- function(winner){
  winner
  win<-data.frame(victories[winner])
  rownames(win)<-win[,1]
  results[winner,rownames(win)]<<-win[,2]
  return(-1)
}
test<- function(k){
  winner<-gagnants[k]
  win<-data.frame(victories[winner])
  rownames(win)<-win[,1]
  return (results[winner,rownames(win)])
}

sapply(gagnants,function (x) fill_victories(x))
results<-replace(results, is.na(results), 0)

test(1)
test(6)
victories[gagnants[5]]
which(!is.na(results[50]))
sum(results[1,])

a<-countsToBinomial(results)
a
```

