---
title: "Preprocess"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
install.packages('BradleyTerry2')
install.packages("stringr", dependencies=TRUE)



```

## R Markdown


```{r cars}
library(stringr)
library(data.table)
d2009=read.csv("2009.csv")
d2010=read.csv("2010.csv")
d2011=read.csv("2011.csv")
d2012=read.csv("2012.csv")
d2013=read.csv("2013.csv")
dall<-list(d2009, d2010, d2011, d2012, d2013)
donnees<-rbindlist(dall, fill=TRUE)
donnees<-as.data.frame(donnees)
```


```{r}
joueurs=union(levels(factor(donnees$Winner)), levels(factor(donnees$Loser)))
n<- length(joueurs)

level_date<-function(df){
  df$Date<-2013-year(as.Date(df$Date, format = "%d/%m/%Y"))
  return (df)
}

aggregate_games<-function(df){
  df<-replace(df, is.na(df), 0)
  df$W<-df$W1+df$W2+df$W3+df$W4+df$W5
  df$L<-df$L1+df$L2+df$L3+df$L4+df$L5
  return (df)
}

prepare_df<-function(df){
  df<-level_date((df))
  df<-aggregate_games(df)
  return(df)
}

fill_results<- function(line,results, alpha){
  w<-(as.numeric(line['W']) * exp(-(alpha*as.numeric(line['Date']))))
  l<-(as.numeric(line['L']) * exp(-(alpha*as.numeric(line['Date']))))
  
  results[as.character(line['Winner']),as.character(line['Loser'])] <<- as.numeric(results[as.character(line['Winner']),as.character(line['Loser'])]) + w
  
  results[as.character(line['Loser']),as.character(line['Winner'])] <<- as.numeric(results[as.character(line['Loser']),as.character(line['Winner'])]) + l
}

process_surface<-function(df,alpha){
  a<-df
  a<-level_date((a))
  a<-aggregate_games(a)
  
  results <<- data.frame(matrix(ncol = n, nrow = n))
  colnames(results)<<-joueurs
  rownames(results)<<-joueurs
  results<<-replace(results, is.na(results), 0)
  apply(a,1,function(x) fill_results(x,results,alpha))
  return(results)
}

process_data<-function(df, alpha){
  X <- split(df,df$Surface)
  Y<-lapply(X,function(x) process_surface(x,alpha))
  return(Y)
}

simple_merge<-function(df){
  y<-Reduce(`+`,df)
  return (y)
}

composed_merge<-function(df,beta){
  y<-simple_merge(df)
  v<-lapply(df,function(x) beta*y+(1-beta)*x)
  return (v)
}
```

```{r}
#process the matrix for each surface, with everygame pondered with exp(-alpha*t) (t=nombre d'années séparant de l'année actuelle)
alpha<-0.05
z<-process_data(donnees,alpha)

z$Grass
z$Clay
z$Hard
z$Carpet

#simple sum of the results for every surface
y<-simple_merge(z)

#matrixes for every surface with the score being 1*main surface score + Beta * (sum of other surfaces score)
beta<-0.1
w<-composed_merge(z,beta)

```

```{r}
alpha<-0.05
z<-process_data(donnees,alpha)

z$Grass
z$Clay
z$Hard
z$Carpet
sum(z)
Reduce(`+`,z)
y<-simple_merge(z)
z
y
w<-composed_merge(z,0)
w
```




